dist: bionic
sudo: false
language: node_js
node_js:
  - "node" # latest stable Node.js release

cache:
  directories:
    - "node_modules" # cache the modules for faster build

script:
  - npm install snyk
  - snyk auth $SNYK_TOKEN
  - snyk test # Check node modules for vulnerability
  - snyk monitor # Update dependencies to snyk

branches:
  only:
  - master # Only build master branch
  - /^greenkeeper.*$/ # Greenkeeper branches
