dist: bionic
sudo: false
language: node_js
node_js:
  - "node" # latest stable Node.js release

cache:
  directories:
    - "node_modules" # cache the modules for faster build

script:
  - npm install standard
  - standard
